### ISSUE TITLE
Junowen's button issue

### ISSUE THREAD

**Issue by polaks12** [progre/junowen#1]
Hi, my friend try to unlock the characters with scoreth19.dat, but when he try to use junowen, he got guided to the online mode, can you help me please

**Comment by progre** [comment]
Before installing Ju.N.Owen, please unlock all characters and make sure you can play official online matches.
Unlocking all characters is currently not supported. This will be addressed in the future by disabling their use.

**Comment by progre** [comment]
fixed https://github.com/progre/junowen/commit/121ce71d30b85b1c708428ddf91f6d8f56a12c6c
