### ISSUE TITLE
Update 1.10c Support

### ISSUE THREAD

**Issue by doremyy** [progre/junowen#11]
After updating to 1.10c, Ju.N.Owen fails to load with a hash mismatch error regarding the th19_junowen.dll file. It changed a handful of things with how the Online VS mode works too, so I assume that there might be some new issues there as well. I know that things like this should be expected to break with the release of a new update, but I just wanted to bring the issue to your attention in any case, and to have it on Github for others to keep track of it!

**Comment by doremyy** [comment]
Bump! Any status report on this? I'd love to be able to play with my friends overseas, and this is the only tool that could facilitate that...

**Comment by progre** [comment]
I'm aware that there are requests regarding this.
I've not been able to work on this matter. I'm a little busy right now.
Please wait a while.
