### ISSUE TITLE
Random Match Suggestion

### ISSUE THREAD

**Issue by CarvajalLlano** [progre/junowen#5]
you can add random match system? like in Official online mode

**Comment by progre** [comment]
It is pseudo-available in shared rooms with the room name "random".
However, after I made this call, user interaction in chat rooms and elsewhere has decreased. From this, I believe that implementing random matches will hinder user interaction.
Therefore, the formal implementation of random matches is currently out of the plan.

**Comment by CarvajalLlano** [comment]
k, understandable 👍
