### ISSUE TITLE
Future plans and Random Matches?

### ISSUE THREAD

**Issue by SuperChrim** [progre/junowen#6]
This patch is simply incredible. You have done amazing work so far. I'm just wondering what you have planned for the future for this project. Do you think you would have the ability to create a random match feature like how there is in the original game? Ideally, it would connect exclusively to other users of this patch. Anyway, thank you for reading.

**Comment by progre** [comment]
Currently, I have no plan. If I may say so, I'm waiting for the official update patch.

About Random Match, There is a duplicate topic. #5

**Comment by SuperChrim** [comment]
Alright. Thank you for responding.
